// templates/vite-svelte-azle/src/components/Counter.svelte
<script lang="ts">
  import { backend } from "../declarations/backend/index.js";

  let count : BigInt = BigInt(0);

  const refreshCounter = async () => {
    const freshCount = await backend.get()
    count = freshCount;
  }

  const increment = async () => {
    await backend.inc()
    await refreshCounter()
  }

  refreshCounter()


</script>
<div class="example">
  <button on:click={increment}>
    Count is {count}
  </button>
</div>

// templates/vite-vue-azle/src/components/Counter.vue
<script setup lang="ts">
  import {ref} from 'vue';
  import { backend } from "../declarations/backend/index.js"
  
  const count = ref(BigInt(0))

  const refreshCounter = async () => {
    const freshCount = await backend.get()
    count.value = freshCount
  }

  const increment = async () => {
    const freshCount = await backend.inc()
    count.value = freshCount
  }

  refreshCounter()
</script>

<template>
  <div class="example">
  <button @click="increment">
    Count is {{ count }}
  </button>
</div>
</template>
