// templates/vite-azle/src/App.tsx
import { useEffect, useState } from 'react';
import './App.css';
import azleLogo from './assets/azle_logo.svg';
import azleShadow from './assets/motoko_shadow.png';
import reactLogo from './assets/react.svg';
import viteLogo from './assets/vite.svg';
import { counter } from './declarations/counter';

function App() {
  const [count, setCount] = useState<number | undefined>();
  const [loading, setLoading] = useState(false);

  // Get the current counter value
  const fetchCount = async () => {
    try {
      setLoading(true);
      const count = await counter.get();
      setCount(+count.toString()); // Convert BigInt to number
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const increment = async () => {
    if (loading) return; // Cancel if waiting for a new count
    try {
      setLoading(true);
      await counter.inc(); // Increment the count by 1
      await fetchCount(); // Fetch the new count
    } finally {
      setLoading(false);
    }
  };

  // Fetch the count on page load
  useEffect(() => {
    fetchCount();
  }, []);

  return (
    <div className="App">
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo vite" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
        <a
          href="https://internetcomputer.org/docs/current/developer-docs/build/cdks/motoko-dfinity/motoko/"
          target="_blank"
        >
          <span className="logo-stack">
            <img
              src={azleShadow}
              className="logo motoko-shadow"
              alt="Motoko logo"
            />
            <img src={azleLogo} className="logo azle" alt="Azle logo" />
          </span>
        </a>
      </div>
      <h1>Vite + React + Azle</h1>
      <div className="card">
        <button onClick={increment} style={{ opacity: loading ? 0.5 : 1 }}>
          count is {count}
        </button>
        <p>
          Edit <code>backend/Backend.mo</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite, React, and Azle logos to learn more
      </p>
    </div>
  );
}

export default App;

// templates/vite-svelte-azle/src/App.svelte
<script lang="ts">
  import './App.css';
  import svelteLogo from './assets/svelte.svg';
  import viteLogo from './assets/vite.svg';
  import azleLogo from './assets/azle_logo.svg';
  import azleShadow from './assets/azle_shadow.png';
  import Counter from './components/Counter.svelte';
</script>

<main>
    <div>
        <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
          <img src={viteLogo} class="logo" alt="Vite Logo" />
        </a>
        <a href="https://svelte.dev" target="_blank" rel="noreferrer">
          <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
        </a>
        <a
          href="https://github.com/demergent-labs/azle"
          target="_blank"
        >
          <span class="logo-stack">
            <img
              src={azleShadow}
              class="logo azle-shadow"
              alt="azle logo"
            />
            <img src={azleLogo} class="logo azle" alt="Azle logo" />
          </span>
        </a>
      </div>
      <h1>Vite + Svelte + Azle </h1>
    
     <Counter />
    
    
      <p class="read-the-docs">
        Click on the Vite, Svelte, and Azle logos to learn more
      </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>
